### ISSUE TITLE
Android8.1系统运行报错java.lang.NoSuchMethodException: registerReceiver

### ISSUE THREAD

**Issue by Hanlen520** [wenxiaomao1023/MixMonkey#1]
java.lang.NoSuchMethodException: registerReceiver [interface android.app.IApplicationThread, class java.lang.String, interface android.content.IIntentReceiver, class android.content.IntentFilter, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getMethod(Class.java:1690)
	at com.android.commands.monkey.u.a(Unknown Source:51)
	at com.android.commands.monkey.Monkey.h(Unknown Source:82)
	at com.android.commands.monkey.Monkey.a(Unknown Source:226)
	at com.android.commands.monkey.Monkey.main(Unknown Source:10)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
** SYS_KEYS has no physical keys but with factor 7.0%.

**Comment by Hanlen520** [comment]
java.lang.NoSuchMethodException: registerReceiver [interface android.app.IApplicationThread, class java.lang.String, interface android.content.IIntentReceiver, class android.content.IntentFilter, class java.lang.String, int]
	at java.lang.Class.getMethod(Class.java:2068)
	at java.lang.Class.getMethod(Class.java:1690)
	at com.android.commands.monkey.u.a(Unknown Source:51)
	at com.android.commands.monkey.Monkey.h(Unknown Source:82)
	at com.android.commands.monkey.Monkey.a(Unknown Source:226)
	at com.android.commands.monkey.Monkey.main(Unknown Source:10)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
** SYS_KEYS_BACK has no physical keys but with factor 16.129032%.

**Comment by wenxiaomao1023** [comment]
非常感谢反馈，已更新1.0.3版本 ：）
